✨ feat: MyPage 1차 구현
BestSprinters/i-Konnect pull request #22
Opened 2024-05-04 04:46 UTC by kim-hye-sun

- 캐러셀 부분 미작업
- 반응형이 아닌 PC작업만 완료

2024-05-06 07:38 UTC, CitrusSoda commented on src/components/CheckedIdolAvatar.jsx
> +function IdolAvatar({ alt, src, size }) {
함수 이름 확인하면 좋을 것 같습니당

2024-05-06 07:38 UTC, CitrusSoda commented on src/pages/MyPage.jsx
> +      setIdols(LimitdIdolList);
filteredIdolList를 setIdols로 바로 넣으면 문제 되는 것이 있을까용? limited로 slice(0, 16)하신 이유가 궁금합니다.

2024-05-06 07:38 UTC, CitrusSoda commented on src/utils/insertLocalStorage.js
> +export default insertLocalStorage;
중복되어 들어오는 데이터까지.. localStorage 만드시느라 고생하셨습니다! 👍

2024-05-06 07:38 UTC, CitrusSoda commented on src/components/IdolThumbnail.jsx
> +    </>
dl태그라니... div와 p, span만 보다가 보니 멋지네요

2024-05-07 04:37 UTC, kim-hye-sun commented on src/pages/MyPage.jsx
> +      setIdols(LimitdIdolList);
관심있는 아이돌 삭제시 아이돌 리스트에 삭제된 아이돌이 추가되는데 슬라이스를 하지 않으면 17개 보여줬다가 16개로 덜컹 거리는것 때문에 슬라이드 16개 넣었습니당 지금은 캐러셀 넣으면서 필요가 없어져서 뺏어용~

2024-05-07 04:37 UTC, kim-hye-sun commented on src/components/CheckedIdolAvatar.jsx
> +function IdolAvatar({ alt, src, size }) {
ㅎ... 감사합니당

2024-05-07 05:37 UTC, CitrusSoda approved these changes
오류 해결을 위해 merge merge

2024-05-07 06:37 UTC, CitrusSoda requested changes
공사중

2024-05-07 20:19 UTC, kim-hye-sun reviewed
준혁님이 크레딧 부분 만드신줄 모르고 이미 푸시를 해버려서...
준혁님이  myPage 브랜치에서 작업하고 계신거 같아서 일단 푸시 취소 안하고 
나중에 리팩토링 할 때 파일 삭제 & 코드 변경하는 방향으로 해볼게요
또 충돌나면 대참사라.... (저 무서워요 ㅠㅠ)
제꺼는 반응형도 안되어있어서 나중에 준혁님껄로 체인지 하겠읍니당

2024-05-08 05:34 UTC, heony704 approved these changes
일단 merge 하고 나중에 리팩토링하는 게 나을 것 같아요

Approve 하겠습니다 ㅎㅎ

2024-05-08 05:35 UTC, Kbomi16 approved these changes

2024-05-08 05:36 UTC, CitrusSoda approved these changes

2024-05-08 07:20 UTC, merged