📦 chore: 폰트 초기 설정
BestSprinters/i-Konnect pull request #3
Opened 2024-04-28 07:22 UTC by Kbomi16

- Pretandard 폰트 파일 추가
- index.css에 폰트 설정 추가
 
![image](https://github.com/Darkthos/i-Konnect/assets/88658551/4ed9f24b-4433-4fde-aad6-ff4bfb5cc122)

tailwind.config.js에 따로 설정하지 않고 전역 css에 넣었습니다. 
피그마 시안에서 폰트 각각 letter-space나 굵기가 제각각이라 클래스명이 길어질 것 같습니다. 그래서 클래스를 따로 만들어두었는데 괜찮은 방법일까요? 나중에 코드 짜실 때 폰트는 클래스명만 쓰실 수 있기 때문에 폰트 부분은 짧게 하고자 했습니다.

2024-04-28 08:45 UTC, CitrusSoda requested changes

2024-04-28 08:45 UTC, CitrusSoda commented on src/index.css
> +}
제 생각은 이 방법은 파일 왔다 갔다 하며 케이스마다 다시 확인해야 돼서 클래스에 따로 weight와 size를 설정하는 게 좋을 것 같아요!
같은 스타일인데 클래스명이 긴 거면 나중에 apply로 만드는 게 좋을 것 같습니다

2024-04-28 08:45 UTC, CitrusSoda commented on src/index.css
> +}
400 하나만 불러서 전체 스타일로 적용한 후 font weight는 따로 설정하는 게 좋을 것 같아요!

2024-04-28 10:46 UTC, Kbomi16 commented on src/index.css
> +}
아 !! 할 때마다 확인해야 해서 번거롭긴 해요.. 수정했습니다!

2024-04-28 10:46 UTC, Kbomi16 commented on src/index.css
> +}
네 ㅎㅎ regular 하나만 있게 설정했습니다 !

2024-04-28 11:01 UTC, CitrusSoda approved these changes
일요일에 대박... 고생하셨어요 👍

2024-04-28 11:01 UTC, CitrusSoda commented on src/App.jsx
> +    <div className="container flex-row items-center justify-center">
혹시 여기 flex 작동 되나용?? 
flex-row는 방향만 지정이라 flex로만 해도 flex 지정해주고 기본이 row라 flex라고만 해도 될 거에요 
container 사용까지 대박 👍

2024-04-29 02:38 UTC, Kbomi16 commented on src/App.jsx
> +    <div className="container flex-row items-center justify-center">
아 !! 그렇군요!! 텍스트 여러개 만들고 몇 개 테일윈드 적용해본다고 테스트겸 뭐 좀 쓰다가 깜박하고 저걸 안 지웠었네용... 나중에 메인이랑 머지되면 필요없는 거라 지우셔도 됩니다 ㅎㅎ!!

2024-04-29 02:48 UTC, heony704 commented on src/index.css
> +}
저도 준혁님 의견에 동의합니다.
그리고 클래스 네임을 한 눈에 알아보기 조금 힘들다고 느껴졌습니다.

2024-04-29 03:04 UTC, heony704 commented on src/index.css
> +}
400 하나만 불러오는 이유가 무엇인가요?

Figma를 확인했을 때는 font-weight을 500도 사용하고 700도 사용하던데
현재 400만 불러오도록 했기 때문에 구체적인 font-weight 설정이 안되고 있는 것 같습니다.

이런 식으로 다양한 설정이 안되고.
![image](https://github.com/BestSprinters/i-Konnect/assets/36994104/06d86416-21b6-4472-ae2c-f1808ae82815)

보시면 이렇게 두 가지 font weight만 적용되는 것 같아요.
![image](https://github.com/BestSprinters/i-Konnect/assets/36994104/ad9da1bf-cf14-4f54-bdd7-12b248eba83d)

2024-04-29 03:44 UTC, Kbomi16 commented on src/index.css
> +}
피그마시안에 따라 bold, semibold, regular, medium 이 4가지만 사용되고 있어, 폰트 다시 추가 설정 해두었습니다. 
폰트 쓰실 때 이렇게 쓰실 수 있습니다.
```<p className="font-bold">안녕하세요.</p>
      <p className="font-semibold">안녕하세요.</p>
      <p className="font-regular">안녕하세요.</p>
      <p className="font-medium">안녕하세요.</p>
```
![image](https://github.com/BestSprinters/i-Konnect/assets/88658551/985ce600-13e8-48d8-a618-f83f38b74833)

2024-04-29 03:57 UTC, CitrusSoda commented on src/index.css
> +}
@heony704 헐 제대로 적용된게 아니였군요!
좀 더 알아보니 폰트 중 Variable폰트가 있는데 이 친구는 하나로 잘 되긴 합니다.

![image](https://github.com/BestSprinters/i-Konnect/assets/49199024/87cca9e3-cac5-44f6-88b4-34376b96cc14)
![image](https://github.com/BestSprinters/i-Konnect/assets/49199024/bcc2a418-de4e-488b-b14e-c62329dc53ad)

4개만 사용하면 수정하신 지금대로 가도 좋을 것 같습니당!

2024-04-29 04:42 UTC, heony704 approved these changes
수고하셨습니다 👍

2024-04-29 04:50 UTC, Darkthos approved these changes
수고하셨습니다.

2024-04-29 04:52 UTC, merged